# Generated by Django 2.0.5 on 2018-06-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name_plural': '标签文章对应表'},
        ),
        migrations.AlterModelOptions(
            name='articledetail',
            options={'verbose_name_plural': '文章详情表'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '博客信息表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '用户自定义分类表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签表'},
        ),
        migrations.AlterModelOptions(
            name='updown',
            options={'verbose_name_plural': '踩赞表'},
        ),
        migrations.AlterModelOptions(
            name='userfans',
            options={'verbose_name_plural': '粉丝表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户信息表'},
        ),
    ]
