# Generated by Django 2.0.5 on 2018-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20180626_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trouble_kill_demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
